// source: https://loremipsum.io/generator/?n=8&t=p
// I generated eight random paragraphs, that's why octopus.
// 
// For each data point I will select a number of characters between a min and max to stand in as annotation for that data point. 
//
// The point is to preserve the design regardless of the length of the text.
export const octopus = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar elementum integer enim neque volutpat ac tincidunt. Vel turpis nunc eget lorem dolor sed viverra. Etiam erat velit scelerisque in dictum non consectetur. Suspendisse interdum consectetur libero id faucibus. Scelerisque eleifend donec pretium vulputate sapien. Vitae aliquet nec ullamcorper sit. Amet justo donec enim diam. Quis lectus nulla at volutpat diam ut venenatis tellus. Sit amet justo donec enim diam. Fringilla est ullamcorper eget nulla. Adipiscing elit ut aliquam purus sit amet luctus. Ac orci phasellus egestas tellus rutrum. Congue eu consequat ac felis donec et odio pellentesque diam.",

    "Veris fermentum odio eu feugiat. Elit sed vulputate mi sit amet. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Cursus risus at ultrices mi tempus. Morbi tristique senectus et netus et malesuada. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. A scelerisque purus semper eget. Donec enim diam vulputate ut. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Tellus elementum sagittis vitae et leo duis ut. Vitae congue eu consequat ac felis donec et. Sed euismod nisi porta lorem. Ac orci phasellus egestas tellus rutrum tellus. Cursus sit amet dictum sit amet justo donec enim diam. Urna condimentum mattis pellentesque id. Aliquam etiam erat velit scelerisque in dictum non consectetur. Pharetra convallis posuere morbi leo urna molestie. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Est lorem ipsum dolor sit amet consectetur adipiscing elit.",

    "Vulputate ut pharetra sit amet aliquam id. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Fermentum odio eu feugiat pretium nibh. Sit amet massa vitae tortor condimentum. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Vestibulum rhoncus est pellentesque elit. Commodo ullamcorper a lacus vestibulum. Massa ultricies mi quis hendrerit. Eget aliquet nibh praesent tristique magna. Sed augue lacus viverra vitae congue eu. At ultrices mi tempus imperdiet nulla. Est sit amet facilisis magna. Aliquam sem et tortor consequat id porta nibh venenatis.",

    "Fringilla phasellus faucibus scelerisque eleifend donec. Curabitur gravida arcu ac tortor dignissim. Neque volutpat ac tincidunt vitae semper quis lectus nulla. Adipiscing bibendum est ultricies integer quis auctor. Leo vel orci porta non pulvinar neque. Egestas erat imperdiet sed euismod nisi porta lorem. Arcu non odio euismod lacinia at quis risus. Est ullamcorper eget nulla facilisi etiam dignissim diam. Varius morbi enim nunc faucibus a pellentesque sit. Dis parturient montes nascetur ridiculus mus mauris. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Enim nunc faucibus a pellentesque. In dictum non consectetur a. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Sagittis vitae et leo duis ut. Id ornare arcu odio ut sem nulla pharetra diam sit. Maecenas accumsan lacus vel facilisis.",

    "Ultrices mi tempus imperdiet nulla malesuada. Neque gravida in fermentum et sollicitudin ac. Consectetur a erat nam at. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Dolor morbi non arcu risus. Magna fringilla urna porttitor rhoncus dolor purus. Etiam erat velit scelerisque in dictum. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Arcu risus quis varius quam quisque id diam. Faucibus vitae aliquet nec ullamcorper sit. Amet cursus sit amet dictum sit amet justo donec. Tellus orci ac auctor augue mauris augue neque gravida. Feugiat sed lectus vestibulum mattis ullamcorper. Tellus id interdum velit laoreet id donec ultrices tincidunt. Ac tincidunt vitae semper quis. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Non pulvinar neque laoreet suspendisse interdum consectetur libero.",

    "Est ultricies integer quis auctor elit sed vulputate. Ut tortor pretium viverra suspendisse potenti nullam ac. Mi sit amet mauris commodo quis imperdiet. Velit egestas dui id ornare arcu odio ut sem nulla. Vitae semper quis lectus nulla at. Ut tortor pretium viverra suspendisse potenti nullam ac. Ipsum consequat nisl vel pretium lectus. Sed blandit libero abacus sed cras ornare arcu dui. Neque laoreet suspendisse interdum consectetur libero id faucibus. Lectus vestibulum mattis ullamcorper velit. Ultrices in iaculis nunc sed augue lacus. Elit ut aliquam purus sit. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Et malesuada fames ac turpis egestas sed tempus urna. Sagittis vitae et leo duis ut diam quam nulla porttitor. Nunc aliquet bibendum enim facilisis gravida. Pulvinar mattis nunc sed blandit libero volutpat sed. In metus vulputate eu scelerisque felis imperdiet proin fermentum.",

    "Astra etiam non quam lacus suspendisse faucibus interdum posuere lorem. Commodo odio aenean sed adipiscing diam. Id cursus metus aliquam eleifend mi. Nunc mattis enim ut tellus elementum. Morbi blandit cursus risus at ultrices mi tempus. Velit egestas dui id ornare arcu odio ut. Diam sit amet nisl suscipit. Lectus mauris ultrices eros in cursus turpis massa. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Cursus turpis massa tincidunt dui ut ornare. Convallis a cras semper auctor neque. Tellus mauris a diam maecenas.",

    "Accumsan lacus vel facilisis volutpat. Auctor neque vitae tempus quam. Sollicitudin tempor id eu nisl nunc mi. Maecenas accumsan lacus vel facilisis volutpat est velit. At tempor commodo ullamcorper a. Sagittis vitae et leo duis ut diam quam nulla. Maecenas sed enim ut sem viverra aliquet. Dictum non consectetur a erat nam at lectus urna duis. Pharetra sit amet aliquam id diam maecenas ultricies. In massa tempor nec feugiat. Faucibus interdum posuere lorem ipsum dolor sit amet. Rutrum quisque non tellus orci ac auctor augue. Varius quam quisque id diam vel quam elementum. Id velit ut tortor pretium viverra. Faucibus vitae aliquet nec ullamcorper sit. Enim ut sem viverra aliquet. Id interdum velit laoreet id donec ultrices.",
]